---
title: "Statistical Modeling"
subtitle: "Stanford University, Hopkins Marine Station"
author: "Winter 2019"
#date: "Instructor: Robin Elahi"
output: 
  html_document: 
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Syllabus

**Course description**  
Introduction to applied statistical modeling in a Bayesian framework. Topics will include probability, regression, model comparison, and hierarchical modeling. We will take a hands-on, computational approach (R, Stan) to gain intuition so that students can later design their own inferential models. Prerequisites for this course include introductory statistics and some calculus or linear algebra, as well as previous exposure to scientific computing. Open to graduate students or undergraduate students with consent of instructor.

We will accomplish the above by:

1. Reading a chapter(s) from *Statistical Rethinking*  prior to each weekly class session. 

2. In class, we will review key concepts and discuss difficult problems. Each class session will be assigned a discussion leader, who will also prepare an .Rmd file with a summary of the key concepts. Then, we will tackle problem sets in class. 

**Instructor**  
Robin Elahi

**Office hours**  
By appointment

**Email**  
elahi at stanford  
Please use your Stanford email for all correspondence

**Course website:**  
Xx

**Times and Rooms:**  
Xx

### Textbook  
Richard McElreath’s Statistical Rethinking:  
[http://xcelab.net/rm/statistical-rethinking/](http://xcelab.net/rm/statistical-rethinking/)

Book can be accessed here:  
[http://proquest.safaribooksonline.com/9781482253481](http://proquest.safaribooksonline.com/9781482253481)

McElreath's lecture slides are [here](https://speakerdeck.com/rmcelreath) and videos of lectures [here](https://www.youtube.com/watch?v=oy7Ks3YfbDg&list=PLDcUM9US4XdM9_N6XUUFrhghGJ4K25bFc)

There are a number of github users who have provided useful companion resources for the text:

[https://github.com/waldronlab/Statistical-Rethinking](https://github.com/waldronlab/Statistical-Rethinking)

[https://github.com/rlabbe/statistical-rethinking](https://github.com/rlabbe/statistical-rethinking)

[https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse](https://github.com/ASKurz/Statistical_Rethinking_with_brms_ggplot2_and_the_tidyverse)

[https://github.com/cavaunpeu/statistical-rethinking](https://github.com/cavaunpeu/statistical-rethinking)

[https://konradsenf.com/further-training/](https://konradsenf.com/further-training/)

[https://github.com/ssp3nc3r/rethinking](https://github.com/ssp3nc3r/rethinking)

[https://github.com/aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3](https://github.com/aloctavodia/Statistical-Rethinking-with-Python-and-PyMC3)

## Schedule

| Week | Day | Date   | Topic                                                       | `rethinking` | Discussion |
|------|-----|--------|-------------------------------------------------------------|--------------|------------|
| 1    | Wed | 09 Jan | Introduction to course; Bayesian approach to inference      | 1, 2         |Robin       |
| 2    | Wed | 16 Jan | Sampling the imaginary                                      | 3            |------------| 
| 3    | Wed | 23 Jan | Linear models                                               | 4            |------------|
| 4    | Wed | 30 Jan | Multivariate linear models                                  | 5            |------------|
| 5    | Wed | 6 Feb  | Overfitting, regularization, information criteria           | 6            |------------|
| 6    | Thu | 14 Feb | Interactions                                                | 7            |------------|
| 7    | Wed | 20 Feb | Markov chain Monte Carlo                                    | 8            |------------|
| 8    | Wed | 27 Feb | Maximum entropy; generalized linear models                  | 9            |------------|
| 9    | Wed | 6 Mar  | Counting and classification                                 | 10           |------------|
| 10   | Wed | 13 Mar | Monsters and mixtures                                       | 11           |------------|
| 11   | Wed | 20 Mar | Multilevel models                                           | 12           |------------|

## Before Class 

### `R` and `RStudio`

Before the first class please read through the [computer setup instructions](00-computer-setup.html) that walk you through how to set up your computer to run R and Rstudio. Even if you have these programs already installed, make sure to check that you are running the latest versions of R and RStudio (which the instructions will tell you how to do). 

Our course website runs from a repository on GitHub. You can view this repository [here](https://github.com/fukamilab/BIO202). Notice that the repository has 2 files for each lesson webpage (named 00-lesson-topic), one is an html file (.html) that is displayed as a webpage while the other is a R markdown (.Rmd) file that will allow us to write R code and explanatory text in the same file. The html file is created by R Studio from the R markdown file. The repository also has a folder called "data". This is where we will put data files used by our example code. Note that this repository can be downloaded by anyone on the internet. If you have data that you wish to use in class but do not wish to share with the entire WWW, you are welcome to email the data files to the rest of the class prior to your lesson.

During class you will be editing the course webpages to include R code for the lesson discussion that you lead. If you are familiar with git and have a GitHub account, you should fork the repository to your account so that you can make changes there. If that is gibberish to you- don't worry! You can either choose to edit the course webpages by downloading them and emailing any edits to Jes (see [computer setup instructions](00-computer-setup.html)) or you can choose to learn a little git and create you own GitHub account during an optional class session during the first week. 


If you are unfamiliar with R and RStudio:  
[Intro to R & RStudio](01-A-R-intro.html)   
[Intro to R markdown](01-B-Rmarkdown-intro.html)


### `rethinking` and `Stan`
